### ISSUE TITLE
"Join Slack" button

### ISSUE THREAD

**Issue by zarela** [swfl-coders/website#10]
Add a button with a call to action for user to join our Slack group.
You can link to the same link we used on the header. Check on `social_media.js` file for exact path.

Here is an example:
![Screen Shot 2019-10-23 at 12 35 35 AM](https://user-images.githubusercontent.com/15879194/67358026-179cdb80-f52d-11e9-81db-ac9dac111808.png)

This is just an example, it can be however you want 😎

**Comment by gnboorse** [comment]
I have created PR #20 for this.
