### ISSUE TITLE
Ensure Social Media Icons go to the proper place

### ISSUE THREAD

**Issue by digitaldrk** [swfl-coders/website#35]
While all icons are accounted for, the links are wrong for some of them.

![image](https://user-images.githubusercontent.com/4297274/96742204-a20e5a00-1390-11eb-939b-d43dd844313b.png)

![image](https://user-images.githubusercontent.com/4297274/96742258-b05c7600-1390-11eb-91fc-9da95e29a215.png)

**Comment by RickyDoss** [comment]
I can fix these

**Comment by RickyDoss** [comment]
Finished this trying to figure out how to do a PR

**Comment by zarela** [comment]
Fixed by PR #40
