### ISSUE TITLE
Add default Card when there are no meetups scheduled

### ISSUE THREAD

**Issue by digitaldrk** [swfl-coders/website#36]
We have a widget that will pull data from the Meetup API and show the next meetup. If there are no meetups scheduled, it says "Our upcoming meetups" and then there's nothing there.

It would be great if there was a 'default' card that said "No meetups scheduled currently"

![image](https://user-images.githubusercontent.com/4297274/96785585-ff200500-13bc-11eb-80c5-eda0e6bd4e1c.png)

![image](https://user-images.githubusercontent.com/4297274/96785626-12cb6b80-13bd-11eb-94f0-d871e3f0fe00.png)

**Comment by walidmujahid** [comment]
I will work on this.
