### ISSUE TITLE
Update Favicon

### ISSUE THREAD

**Issue by digitaldrk** [swfl-coders/website#37]
Currently our site uses the favicon that ships with our static site generator, [Gatsby](https://www.gatsbyjs.com/)

It would be great to have a custom favicon that is more along our branding. Maybe the glasses.

It'd need to work with dark mode I think.

![image](https://user-images.githubusercontent.com/4297274/96892940-2bd52a80-1458-11eb-86da-e91dbdbd68ca.png)

**Comment by RickyDoss** [comment]
I made a new icon for this, I can take the issue.
