### ISSUE TITLE
Fix menu items alignment on nav bar

### ISSUE THREAD

**Issue by zarela** [swfl-coders/website#38]
Currently menu items are opposite to each other. We would like to have them next to each other, as we will continue adding items later on.
<img width="1400" alt="Screen Shot 2020-10-23 at 12 04 07 AM" src="https://user-images.githubusercontent.com/15879194/96955337-5b6d4c80-14c3-11eb-8a77-1cb3d517162e.png">

**Comment by RickyDoss** [comment]
I have completed this issue and am working on PR

**Comment by zarela** [comment]
Fixed by commit #39
