### ISSUE TITLE
Add YouTube to social media icons section

### ISSUE THREAD

**Issue by zarela** [swfl-coders/website#42]
We now have also a YouTube channel, please link to:
https://www.youtube.com/channel/UCddevqVraYVVQHJTbPTf5oA

**NOTE**: Please make sure the icons are showing on both header and footer.

<img width="241" alt="Screen Shot 2020-10-24 at 10 49 13 PM" src="https://user-images.githubusercontent.com/15879194/97097795-9ac6a500-164b-11eb-8440-d5e903433fdc.png">

**Comment by RickyDoss** [comment]
I can fix this

**Comment by RickyDoss** [comment]
Subbing PR; However for some reason github is merging my previous commits with my new commit for this issue.

**Comment by RickyDoss** [comment]
Appears that commit 56451dc is a child to commit e1ee0d4 (parent). Need to figure out how to remove the parent, possibly rebase?

**Comment by digitaldrk** [comment]
Just push what you have, submit a PR and we'll figure it out. 👍
