### ISSUE TITLE
Change text next to Favicon

### ISSUE THREAD

**Issue by zarela** [swfl-coders/website#43]
Currently when our site is open, shows the entire website url.
Please check the text to be **SWFL Coders**

<img width="338" alt="Screen Shot 2020-10-24 at 10 48 59 PM" src="https://user-images.githubusercontent.com/15879194/97097869-9bac0680-164c-11eb-99e4-e0ab96633e27.png">

**Comment by RickyDoss** [comment]
I can take this

**Comment by RickyDoss** [comment]
completed this issue; However, the index.html file is in the public folder while the public folder is set to .gitignore. Once this is fixed, I can pull from origin master then add, commit, and push change. Will create PR after this.

**Comment by digitaldrk** [comment]
closed by #44
