### ISSUE TITLE
Fix nav bar and header on company_directory page

### ISSUE THREAD

**Issue by zarela** [swfl-coders/website#5]
Header and nav bar on home page is across the width of the page, but when you navigate to the company directory page is not. 
Please helps us fix it so it matches the home page.

**Comment by PabloPap** [comment]
can i take this?

**Comment by digitaldrk** [comment]
> can i take this?

Oh yeah :)

**Comment by PabloPap** [comment]
@digitaldrk I cannot push because don't have access to the repo, can you add me as collaborator?

**Comment by digitaldrk** [comment]
Hey @PabloPap I think you're gonna have to make a fork of the Repository and submit a Pull Request Like this:

https://github.com/swfl-coders/website/pull/12
