### ISSUE TITLE
"Join Meetup" button

### ISSUE THREAD

**Issue by zarela** [swfl-coders/website#9]
Add a call to action for users to register as members to our meetup page
https://www.meetup.com/SWFL-Coders/

Bonus: If you can, it will be cool to add a counter to the button of how many members we have.
You can use the Meetup API we are using to get this number.

Here is an example:
![Screen Shot 2019-10-23 at 12 28 31 AM](https://user-images.githubusercontent.com/15879194/67357716-22a33c00-f52c-11e9-9ceb-7265a5c987a3.png)

It does not need to be exactly like that. Feel free to use your own 

This is just an example, it can be however you want 😎

**Comment by brian-digital-labs** [comment]
I'd like to have a go at this.
